server:
  port: 801

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: mysql
    url: jdbc:mysql://127.0.0.1:3306/Test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
    initialSize: 10
    maxActive: 100
    minIdle: 10
    maxWait: 6000


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/resources/mapper/*

#  druid:
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 10
#    maxIdle: 15
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    maxOpenPreparedStatements: 20
#    removeAbandoned: true
#    removeAbandonedTimeout: 1800
#    logAbandoned: true
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#  redis:
#    database: 1  # Redis数据库索引（默认为0） # Redis数据库索引（默认为0）
#    host: 127.0.0.1   # Redis服务器地址
#    port: 6379     # Redis服务器连接端口
#    password:   # Redis服务器连接密码（默认为空)
#    timeout: 1000  # 连接超时时间（毫秒）
#    jedis:
#      pool:
#        max-active: 100
#        max-wait: 1000
#        max-idle: 10
#        min-idle: 10


#  type-aliases-package: com.example.demo.entity

